### ISSUE TITLE
React Hook useEffect has a missing dependency: 'fetchTransactions'. Either include it or remove the dependency array.

### ISSUE THREAD

**Issue by okunamayanad** [tkbstudios/CC-Bank-frontend#15]
at [dashboard/page.tsx:355](https://github.com/tkbstudios/CC-Bank-frontend/blob/a8cf7a0b31139348155cdcb6e22fa473e8a1cc99/src/app/dashboard/page.tsx#L355)

Including `fetchTransactions` in the dependency array triggers more errors. Don't have time to dig into this right now so I'm opening an issue to come back to later.

**Comment by tkbstudios** [comment]
Please update your fork, this isn't in the main nor dev branch here

**Comment by okunamayanad** [comment]
It's still in the dev branch and I've [linked it here](https://github.com/tkbstudios/CC-Bank-frontend/blob/a8cf7a0b31139348155cdcb6e22fa473e8a1cc99/src/app/dashboard/page.tsx#L355).
Introduced in #8 when moving fetching transactions to a function.
It's not a major problem, but a warning that can cause problems in the future.
Please check again using `pnpm lint` on dev branch.

**Comment by okunamayanad** [comment]
> I only see this :/ ![Screenshot_20240410_181027_Firefox](https://private-user-images.githubusercontent.com/69647028/321313546-2e039998-d359-4ef8-88b6-4f1c0dd4bcb4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NzA0NDUsIm5iZiI6MTcxMjg3MDE0NSwicGF0aCI6Ii82OTY0NzAyOC8zMjEzMTM1NDYtMmUwMzk5OTgtZDM1OS00ZWY4LTg4YjYtNGYxYzBkZDRiY2I0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDIxMTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNGNhZmE5MWNmYmQwNGMxMjZlNTMzOGQ2NzNiMTA3MTE3YzQ5ZDQ5ODgxM2U3NGQxZDU3NGI4MDZkMzJkMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iyu4UnUfZIIe-hdLtAbHnSEnTi897fmay3xqJeCiDKw)

That is actually correct behaviour. I've linked that line because it is because of that line. It doesn't have `fetchTransactions` although it's now fixed by #21
