### ISSUE TITLE
Making Transactions

### ISSUE THREAD

**Issue by okunamayanad** [tkbstudios/CC-Bank-frontend#4]
A button that will open up a dialog for sending a transaction
![Image](https://github.com/tkbstudios/CC-Bank-frontend/assets/108594296/226305be-f981-4f6b-9594-312ca88d1e31)

The dialog will be in style of responsive dialogs seen in login, logout and inspect buttons

**Comment by tkbstudios** [comment]
https://github.com/tkbstudios/CC-Bank-frontend/commit/d1920361d0e5b9c9c3d21f0c19ecbcd9074958d2
there u go
