### ISSUE TITLE
Move dashboard to /dashboard/

### ISSUE THREAD

**Issue by okunamayanad** [tkbstudios/CC-Bank-frontend#5]
Curently /dashboard/perPage/page

Final: /dashboard?per_page=15&page=1

**Comment by tkbstudios** [comment]
Why not make it ?dashboard simply and put the per_page and page in the code?

**Comment by okunamayanad** [comment]
> Why not make it ?dashboard simply and put the per_page and page in the code?

/dashboard is meant to be another page, not a search query

**Comment by okunamayanad** [comment]
Closing this with #12
